#server:
#  port: 8002
#
#spring:
#  application:
#    name: location-manage
#  cloud:
#    sentinel:
#      transport:
#        dashboard: 127.0.0.1:9000
#        port: 9001
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/location?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
#
## 控制台输出sql、下划线转驼峰
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath:dao/*.xml
